### ISSUE TITLE
Add some form of CI

### ISSUE THREAD

**Issue by gavanderhoorn** [rosin-project/haros_catkin#21]
Could probably run analysis on some package, perhaps even [haros_catkin_test](https://github.com/ipa-jfh/haros_catkin_test).

That would give us an idea of whether any changes in PRs break something.

**Comment by nlimpert** [comment]
Sounds good - would you think of Travis?

Using Travis requires owner permissions of a GitHub repository afaik.

**Comment by gavanderhoorn** [comment]
> Sounds good - would you think of Travis?

Yes. More specifically, just using [industrial_ci](https://github.com/ros-industrial/industrial_ci).

> Using Travis requires owner permissions of a GitHub repository afaik.

Just to enable the hooks. After that it's not needed.

I've just enabled it for this repository.

**Comment by nlimpert** [comment]
A short update on this:

My [first try](https://github.com/nlimpert/haros_catkin/blob/79c54bdd5ccdab910a966359874c101b2d6b1ad5/.travis.yml#L26) to execute `haros_report` for the `test_pkg` of `haros_catkin_test` won't execute the macro as our current setup expects `haros_report` to be a `catkin-make-arg` and not a `cmake-arg`.
However, `industrial_ci` won't allow setting a `catkin-make-arg` (yet).

Then I tried to execute `haros` as a `rostest` but apparently this fails too because `haros` won't allow unknown arguments (`rostest` expects the node to accept arguments like `--gtest_output=xml:/path/to/output.xml`)

I'll see whether I can achieve this by using industrial_ci's `AFTER_SCRIPT` feature.

**Comment by gavanderhoorn** [comment]
> My [first try](https://github.com/nlimpert/haros_catkin/blob/79c54bdd5ccdab910a966359874c101b2d6b1ad5/.travis.yml#L26) to execute `haros_report` for the `test_pkg` of `haros_catkin_test` won't execute the macro as our current setup expects `haros_report` to be a `catkin-make-arg` and not a `cmake-arg`.

I'm not sure this is actually true.

The [target added to the build](https://github.com/rosin-project/haros_catkin/blob/3447642e4cb7eaf0e3fda55ed9b928463545da40/cmake/haros_catkin-extras.cmake.em#L8) in the end gets translated into a regular `make` target, so it should be runnable by just doing something like `make haros_report` (in the correct build dir).

**Comment by nlimpert** [comment]
> I'm not sure this is actually true.
> 
> The [target added to the build](https://github.com/rosin-project/haros_catkin/blob/3447642e4cb7eaf0e3fda55ed9b928463545da40/cmake/haros_catkin-extras.cmake.em#L8) in the end gets translated into a regular `make` target, so it should be runnable by just doing something like `make haros_report` (in the correct build dir).

Thanks for the notice! You were right - it's executable as a `make` target. I have [added this](https://github.com/nlimpert/haros_catkin/blob/6b1fcc9a0c98346fc8a62f866ff4bd88e74249ea/test_haros_report.sh) in a script executed as `AFTER_SCRIPT`.

I'll create a PR asap.
